package com.kubukoz

import cats.effect.ExitCode
import cats.effect.IO
import cats.effect.IOApp
import com.amazonaws.dynamodb._

object ForceActivate extends IOApp {

  def run(args: List[String]): IO[ExitCode] = Commons
    // Note: DynamoDB is a type alias for a pretty huge trait.
    // Reproducing this with a simpler interface wasn't trivial so I kept it.
    // DynamoDB comes from code generated by smithy4s.
    .backend(DynamoDB)[IO](local = false)
    .use { dynamop =>
      dynamop
        .getItem("a", Map.empty)
        .run
        .flatMap { out =>
          IO.println(
            ()
          )
        }
    }
    .as(ExitCode.Success)

}
