pull_request_rules:
  - name: backport labeled PRs to the 0.19 branch
    conditions:
      - label="backport-0.19"
    actions:
      backport:
        branches:
          - "series/0.19"

  - name: automatically merge backport if they pass tests
    conditions:
      - author=mergify[bot]
      - head~=^mergify/bp/
      - base="series/0.19"
    actions:
      merge:
        method: merge
