package com.amazonaws.dynamodb

import smithy4s.Schema
import smithy4s.Hints
import smithy4s.ShapeId
import smithy4s.schema.Schema.struct
import smithy4s.ShapeTag

case class BatchWriteItemOutput(unprocessedItems: Option[Map[TableName,List[WriteRequest]]] = None, itemCollectionMetrics: Option[Map[TableName,List[ItemCollectionMetrics]]] = None, consumedCapacity: Option[List[ConsumedCapacity]] = None)
object BatchWriteItemOutput extends ShapeTag.Companion[BatchWriteItemOutput] {
  val id: ShapeId = ShapeId("com.amazonaws.dynamodb", "BatchWriteItemOutput")

  val hints : Hints = Hints(
    smithy.api.Documentation("<p>Represents the output of a <code>BatchWriteItem</code> operation.</p>"),
  )

  implicit val schema: Schema[BatchWriteItemOutput] = struct(
    BatchWriteItemRequestMap.underlyingSchema.optional[BatchWriteItemOutput]("UnprocessedItems", _.unprocessedItems).addHints(smithy.api.Documentation("<p>A map of tables and requests against those tables that were not processed. The\n                <code>UnprocessedItems</code> value is in the same form as\n            <code>RequestItems</code>, so you can provide this value directly to a subsequent\n                <code>BatchGetItem</code> operation. For more information, see\n                <code>RequestItems</code> in the Request Parameters section.</p>\n        <p>Each <code>UnprocessedItems</code> entry consists of a table name and, for that table,\n            a list of operations to perform (<code>DeleteRequest</code> or\n            <code>PutRequest</code>).</p>\n        <ul>\n            <li>\n                <p>\n                    <code>DeleteRequest</code> - Perform a <code>DeleteItem</code> operation on the\n                    specified item. The item to be deleted is identified by a <code>Key</code>\n                    subelement:</p>\n                <ul>\n                  <li>\n                        <p>\n                            <code>Key</code> - A map of primary key attribute values that uniquely\n                            identify the item. Each entry in this map consists of an attribute name\n                            and an attribute value.</p>\n                    </li>\n               </ul>\n            </li>\n            <li>\n                <p>\n                    <code>PutRequest</code> - Perform a <code>PutItem</code> operation on the\n                    specified item. The item to be put is identified by an <code>Item</code>\n                    subelement:</p>\n                <ul>\n                  <li>\n                        <p>\n                            <code>Item</code> - A map of attributes and their values. Each entry in\n                            this map consists of an attribute name and an attribute value. Attribute\n                            values must not be null; string and binary type attributes must have\n                            lengths greater than zero; and set type attributes must not be empty.\n                            Requests that contain empty values will be rejected with a\n                                <code>ValidationException</code> exception.</p>\n                        <p>If you specify any attributes that are part of an index key, then the\n                            data types for those attributes must match those of the schema in the\n                            table\'s attribute definition.</p>\n                    </li>\n               </ul>\n            </li>\n         </ul>\n        <p>If there are no unprocessed items remaining, the response contains an empty\n                <code>UnprocessedItems</code> map.</p>")),
    ItemCollectionMetricsPerTable.underlyingSchema.optional[BatchWriteItemOutput]("ItemCollectionMetrics", _.itemCollectionMetrics).addHints(smithy.api.Documentation("<p>A list of tables that were processed by <code>BatchWriteItem</code> and, for each\n            table, information about any item collections that were affected by individual\n                <code>DeleteItem</code> or <code>PutItem</code> operations.</p>\n        <p>Each entry consists of the following subelements:</p>\n        <ul>\n            <li>\n                <p>\n                    <code>ItemCollectionKey</code> - The partition key value of the item collection.\n                    This is the same as the partition key value of the item.</p>\n            </li>\n            <li>\n                <p>\n                    <code>SizeEstimateRangeGB</code> - An estimate of item collection size,\n                    expressed in GB. This is a two-element array containing a lower bound and an\n                    upper bound for the estimate. The estimate includes the size of all the items in\n                    the table, plus the size of all attributes projected into all of the local\n                    secondary indexes on the table. Use this estimate to measure whether a local\n                    secondary index is approaching its size limit.</p>\n                <p>The estimate is subject to change over time; therefore, do not rely on the\n                    precision or accuracy of the estimate.</p>\n            </li>\n         </ul>")),
    ConsumedCapacityMultiple.underlyingSchema.optional[BatchWriteItemOutput]("ConsumedCapacity", _.consumedCapacity).addHints(smithy.api.Documentation("<p>The capacity units consumed by the entire <code>BatchWriteItem</code>\n            operation.</p>\n        <p>Each element consists of:</p>\n        <ul>\n            <li>\n                <p>\n                    <code>TableName</code> - The table that consumed the provisioned\n                    throughput.</p>\n            </li>\n            <li>\n                <p>\n                    <code>CapacityUnits</code> - The total number of capacity units consumed.</p>\n            </li>\n         </ul>")),
  ){
    BatchWriteItemOutput.apply
  }.withId(id).addHints(hints)
}