package com.amazonaws.dynamodb

import smithy4s.Schema
import smithy4s.Hints
import smithy4s.ShapeId
import smithy4s.schema.Schema.struct
import smithy4s.ShapeTag

case class GetItemInput(tableName: TableName, key: Map[AttributeName,AttributeValue], attributesToGet: Option[List[AttributeName]] = None, consistentRead: Option[ConsistentRead] = None, returnConsumedCapacity: Option[ReturnConsumedCapacity] = None, projectionExpression: Option[ProjectionExpression] = None, expressionAttributeNames: Option[Map[ExpressionAttributeNameVariable,AttributeName]] = None)
object GetItemInput extends ShapeTag.Companion[GetItemInput] {
  val id: ShapeId = ShapeId("com.amazonaws.dynamodb", "GetItemInput")

  val hints : Hints = Hints(
    smithy.api.Documentation("<p>Represents the input of a <code>GetItem</code> operation.</p>"),
  )

  implicit val schema: Schema[GetItemInput] = struct(
    TableName.schema.required[GetItemInput]("TableName", _.tableName).addHints(smithy.api.Documentation("<p>The name of the table containing the requested item.</p>"), smithy.api.Required()),
    Key.underlyingSchema.required[GetItemInput]("Key", _.key).addHints(smithy.api.Documentation("<p>A map of attribute names to <code>AttributeValue</code> objects, representing the\n            primary key of the item to retrieve.</p>\n        <p>For the primary key, you must provide all of the attributes. For example, with a\n            simple primary key, you only need to provide a value for the partition key. For a\n            composite primary key, you must provide values for both the partition key and the sort\n            key.</p>"), smithy.api.Required()),
    AttributeNameList.underlyingSchema.optional[GetItemInput]("AttributesToGet", _.attributesToGet).addHints(smithy.api.Documentation("<p>This is a legacy parameter. Use <code>ProjectionExpression</code> instead. For more\n            information, see <a href=\"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LegacyConditionalParameters.AttributesToGet.html\">AttributesToGet</a> in the <i>Amazon DynamoDB Developer\n            Guide</i>.</p>")),
    ConsistentRead.schema.optional[GetItemInput]("ConsistentRead", _.consistentRead).addHints(smithy.api.Box(), smithy.api.Documentation("<p>Determines the read consistency model: If set to <code>true</code>, then the operation\n            uses strongly consistent reads; otherwise, the operation uses eventually consistent\n            reads.</p>")),
    ReturnConsumedCapacity.schema.optional[GetItemInput]("ReturnConsumedCapacity", _.returnConsumedCapacity),
    ProjectionExpression.schema.optional[GetItemInput]("ProjectionExpression", _.projectionExpression).addHints(smithy.api.Documentation("<p>A string that identifies one or more attributes to retrieve from the table. These\n            attributes can include scalars, sets, or elements of a JSON document. The attributes in\n            the expression must be separated by commas.</p>\n        <p>If no attribute names are specified, then all attributes are returned. If any of the\n            requested attributes are not found, they do not appear in the result.</p>\n        <p>For more information, see <a href=\"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html\">Specifying Item Attributes</a> in the <i>Amazon DynamoDB Developer\n                Guide</i>.</p>")),
    ExpressionAttributeNameMap.underlyingSchema.optional[GetItemInput]("ExpressionAttributeNames", _.expressionAttributeNames).addHints(smithy.api.Documentation("<p>One or more substitution tokens for attribute names in an expression. The following\n            are some use cases for using <code>ExpressionAttributeNames</code>:</p>\n        <ul>\n            <li>\n                <p>To access an attribute whose name conflicts with a DynamoDB reserved\n                    word.</p>\n            </li>\n            <li>\n                <p>To create a placeholder for repeating occurrences of an attribute name in an\n                    expression.</p>\n            </li>\n            <li>\n                <p>To prevent special characters in an attribute name from being misinterpreted\n                    in an expression.</p>\n            </li>\n         </ul>\n        <p>Use the <b>#</b> character in an expression to dereference\n            an attribute name. For example, consider the following attribute name:</p>\n        <ul>\n            <li>\n                <p>\n                    <code>Percentile</code>\n                </p>\n            </li>\n         </ul>\n        <p>The name of this attribute conflicts with a reserved word, so it cannot be used\n            directly in an expression. (For the complete list of reserved words, see <a href=\"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html\">Reserved Words</a> in the <i>Amazon DynamoDB Developer\n            Guide</i>). To work around this, you could specify the following for\n                <code>ExpressionAttributeNames</code>:</p>\n        <ul>\n            <li>\n                <p>\n                    <code>{\"#P\":\"Percentile\"}</code>\n                </p>\n            </li>\n         </ul>\n        <p>You could then use this substitution in an expression, as in this example:</p>\n        <ul>\n            <li>\n                <p>\n                    <code>#P = :val</code>\n                </p>\n            </li>\n         </ul>\n        <note>\n            <p>Tokens that begin with the <b>:</b> character are\n                    <i>expression attribute values</i>, which are placeholders for the\n                actual value at runtime.</p>\n        </note>\n        <p>For more information on expression attribute names, see <a href=\"https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.AccessingItemAttributes.html\">Specifying Item Attributes</a> in the <i>Amazon DynamoDB Developer\n                Guide</i>.</p>")),
  ){
    GetItemInput.apply
  }.withId(id).addHints(hints)
}